#!/bin/bash

# Default value
SERVICE=""

# Parse command line options
while getopts ":c:" opt; do
  case $opt in
    c)
      SERVICE="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Check if required option is provided
if [ -z "$SERVICE" ]; then
  echo "Usage: $(basename "$0") -c <service>"
  exit 1
fi

# Check if the service is running
if ps ax | grep -v grep | grep -v "$(basename "$0")" | grep -q "$SERVICE"; then
    echo "OK - $SERVICE service is running"
    exit 0  # Exit with status 0 (OK)
else
    echo "CRITICAL - $SERVICE service is not running"
    exit 2  # Exit with status 2 (CRITICAL)
fi
